### PR TITLE
Feature/reset with exceptions

### PR DESCRIPTION
**Pull request by jkage**
make sure to review the frontend too here https://github.com/texttochange/vusion-frontend/pull/230

### CODE REVIEW

**Comment by jkage** [comment]
@overnin please review

**Comment by jkage** [comment]
@overnin please review

**Comment by overnin** [comment]
@jkage i still doubt about the getting scheduled, can you please explain if the participant get auto-enrolled on dialogues with the except tags and labels.

**Comment by jkage** [comment]
@overnin Yes, the participant gets auto-enrolled on dialogues if the tags and labels that he keeps are used as auto-enrollment subconditions.

**Comment by jkage** [comment]
@markphi2013 please review.
Test that:
- [ ] when "keep tags" and "keep labels" are empty, all tags and labels are deleted.
- [ ] tag(s) are kept.
- [ ] label(s) are kept
- [ ] auto-enroll base on tag(s) or label(s) works after the rest action.

**Comment by markphi2013** [comment]
ok for merge

**Pull request merged**
