### PR TITLE
refactor export to provide better UX

### PR DESCRIPTION
**Pull request by overnin**

### CODE REVIEW

**Comment by markphi2013** [comment]
One test is failing:

**Comment by markphi2013** [comment]
one test is failing : 
::
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/var/vusion/backend/ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/var/vusion/backend/vusion/tests/test_export_worker.py", line 221, in test_export_unmatchable_reply
    conditions={}))
  File "/var/vusion/backend/vusion/persist/model.py", line 25, in __init__
    self.validate_fields()
  File "/var/vusion/backend/vusion/persist/export/export.py", line 65, in validate_fields
    self._validate(self, Export.fields)
  File "/var/vusion/backend/vusion/persist/model.py", line 107, in _validate
    raise InvalidField("%s=%s is not %s" % (field, data[field], rule_name))
vusion.error.InvalidField: collection=unmatchable-reply is not 2_valid_value

vusion.tests.test_export_worker.ExportWorkerTestCase.test_export_unmatchable_reply
-------------------------------------------------------------------------------
Ran 379 tests in 21.768s

FAILED (errors=1, successes=378)

**Comment by overnin** [comment]
@markphi2013 test fixed

**Comment by markphi2013** [comment]
Ok for merge

**Pull request merged**
